# Change these first
owner: Jim-Paul # Your GitHub organization or username, where this repository lives
repo: Upptime-Status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Upptime-Status
  logoUrl: https://github.com/Jim-Paul/Upptime-Status/blob/master/assets/Untitled%20(54%20x%2054%20px).svg
  name: Quantumica Status Page
  introTitle: "Welcome to the official status page for **Quantumica** a technology company committed to reliability and performance."
  introMessage: This page provides **real-time** updates on the operational status of our endpoints.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Jim-Paul/Upptime-Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
